### ISSUE TITLE
Incorrect number of trials for RVG16_B01

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/nsds_lab_to_nwb#114]
There are only 118 trials list for `/clusterfs/NSDS_data/nwb/test/RVG16/RVG16_B01.nwb` but there should be 120 (60 for stimulus and 60 for baseline). 

![image](https://user-images.githubusercontent.com/5800317/132917297-19908bb9-1ba0-4434-9614-e7aa38c52ea2.png)

**Comment by jihyunbak** [comment]
We were missing the first mark in wn2 blocks - this can be fixed if a lower threshold was used (0.1 instead of 0.3), as implemented in PR #130. We had the same observation before (for example #102), but we understand a little better now: the first mark is smaller than all the other markers in the recorded mark time series.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/39214579/155079046-83a879d0-45c5-4964-8ff9-c2deb19778dc.png">


This is probably because the mark for wn2 starts right at the beginning of the audio file (although not sure exactly why)...

<img width="574" alt="image" src="https://user-images.githubusercontent.com/39214579/155079211-2abe3bc5-5390-4057-8f68-602a64956934.png">
