### ISSUE TITLE
need subject metadata for old experiments

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#47]
specifically:
- sex
- species
- genotype
- description (where the animal came from)
- weight

**Comment by jihyunbak** [comment]
@VBaratham Would the experiment notes from cadmus (the txt/rtf files you've found last week and copied to catscan) be the only source for this?

**Comment by VBaratham** [comment]
Those are the only ones I know of, but I wouldn't be surprised if there
were more on the rig machine that didn't make it to cadmus

**Comment by jthermiz** [comment]
I think Max only used female, Sprague Dawley, wild type rats. Weight information can be found below if you want to parse it. The animals came probably came from Charles River, but I don't think there's an easy way to verify this. We could ask Max or just leave it blank since I don't think it's that important information.

Weight info
https://docs.google.com/spreadsheets/d/1EUythTt9ZAhZ4KvNTkUyU8oeS5j_CLifHYRFZ0inAXI/edit#gid=0

@vngutierrez  can you go spot check the animal experiment logs to confirm sex, species and genotype?

**Comment by maxdougherty** [comment]
@jthermiz That is correct. I only used female Sprague Dawley albino wild type rats. All rats were ordered from Charles River. At one point I started requesting a specific Charles River facility. Gaby should be able to pull up those old purchase records.

**Comment by jihyunbak** [comment]
@jthermiz @vngutierrez I included the weight info in the google sheet as a metadata resource (see the new file `old_subject_metadata.yaml` added as part of PR #74).

Quick question: are older rat weights (<R39) not available?
